---
- name: uri module demo
  hosts: localhost
  become: false
  vars:
    server: "https://verintamericas.saas.appdynamics.com"
    endpoint: "/controller/alerting/rest/v1/applications/4358/health-rules"
  tasks:
    - name: Reading CPU Usage-QA2
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        user: Sankumar@verintamericas
        password: QAZ123plm$$
        force_basic_auth: yes
        return_content: yes
        method: GET
        status_code: 200
        timeout: 30
      register: result

    - name: CPU Usage for QA2
      ansible.builtin.debug:
        var: result.content
        
